package com.mcf.davidee.spawneggs;

import java.util.Arrays;

import net.minecraft.block.BlockDispenser;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;

import com.mcf.davidee.spawneggs.eggs.DispenserBehaviorSpawnEgg;
import com.mcf.davidee.spawneggs.eggs.ItemSpawnEgg;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = "SpawnEggs", name="Better Spawn Eggs",version="1.7.2.0")
public class SpawnEggsMod {

	@Instance("SpawnEggs")
	private static SpawnEggsMod instance;

	public static CreativeTabs tabSpawnEggs = new CreativeTabs("spawnEggs") {
		@Override
		public Item getTabIconItem() {
			return spawnEgg;
		}
	};

	public static ItemSpawnEgg spawnEgg;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		spawnEgg = new ItemSpawnEgg();

		GameRegistry.registerItem(spawnEgg, spawnEgg.getUnlocalizedName());
		BlockDispenser.dispenseBehaviorRegistry.putObject(spawnEgg, new DispenserBehaviorSpawnEgg());
		
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Davidee" });
		modMeta.autogenerated = false;
		modMeta.credits = "Thanks to Mojang, Forge, and all your support.";
		modMeta.description = "Adds advanced spawn eggs into Minecraft.\n"
				+ "These spawn eggs can be customized using NBTEdit.\n"
				+ "For more information, visit the URL above.";
		modMeta.url = "http://www.minecraftforum.net/topic/1882749-/";
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		
	}
	
	@EventHandler 
	public void postInit(FMLPostInitializationEvent event) {
		DefaultFunctionality.addAllSpawnEggs();
	}
	
}
